name: Build and Deploy to Cloud Run

on:
  push:
    paths:
      - 'test1/**'
      - 'test2/**'
  pull_request:
    branches:
      - master

env:
  PROJECT_ID: prj-airindia-poc-01 # TODO: update Google Cloud project id
  GAR_LOCATION: asia-south1  # TODO: update Artifact Registry location
  REGION: asia-south1 # TODO: update Cloud Run service region

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/13579727091/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: 'sql-poc@prj-airindia-poc-01.iam.gserviceaccount.com' # e.g. - my-service-account@my-project.iam.gserviceaccount.com
          access_token_lifetime: '300s'



######## working yaml################
      # NOTE: Alternative option - authentication via credentials json

      ### - id: "auth"
      #   uses: google-github-actions/auth@v1.1.1
      #   with:
      #     credentials_json: "${{ secrets.SA }}"

      ### Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)

      ###working suhas
      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        if: startsWith(github.event_path, 'test1/')
        run: |-
          docker build -t "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test1:${{ github.sha }}" ./
          docker push "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test1:${{ github.sha }}"

      - name: Build and Push Container
        if: startsWith(github.event_path, 'test2/')
        run: |-
          docker build -t "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:${{ github.sha }}" ./
          docker push "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:${{ github.sha }}"

      # # # END - Docker auth and build

      # - name: Deploy to VM
      #   id: 'compute-ssh'
      #   uses: 'google-github-actions/ssh-compute@v1'
      #   with:
      #     instance_name: 'docker-cicd'
      #     zone: 'asia-south1-c'
      #     ssh_private_key: '${{ secrets.GCP_SSH_PRIVATE_KEY }}'
      #     command: |
      #       # sudo docker stop $(sudo docker ps -aq)
      #       # sudo docker rm $(sudo docker ps -aq)
      #       sudo docker stop app-1
      #       sudo docker rm app-1
      #       sudo docker rmi $(sudo docker images -q)
      #       sudo docker pull asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test:${{ github.sha }}
      #       sudo docker pull asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:${{ github.sha }}
      #       sudo docker pull asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test3:${{ github.sha }}
      #       sudo docker run --name app-1 -d -p 8080:8080 asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test:${{ github.sha }}
      #       sudo docker run --name app-2 -d -p 8080:8080 asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:${{ github.sha }}
      #       sudo docker run --name app-3 -d -p 8080:8080 asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test3:${{ github.sha }}
          
        

      # # # If required, use the Cloud Run url output in later steps
      # - name: Show Output
      #   run: |-
      #     echo '${{ steps.compute-ssh.outputs.stdout }}'
      #     echo '${{ steps.compute-ssh.outputs.stderr }}' 
