name: Build and Deploy to Cloud Run

# on:
#   push:
#     branches:
#     - master
#     paths:
#       - 'test1/**' # Trigger only when changes are made in test1 folder
#       - 'test2/**' # Trigger only when changes are made in test2 folder
#   pull_request:
#     branches:
#     - master
#     paths:
#       - 'test1/**'
#       - 'test2/**'

on:
  push:
    paths:
      - 'test1/**' # Trigger only when changes are made in test1 folder
      - 'test2/**' # Trigger only when changes are made in test2 folder
  pull_request:
    paths:
      - 'test1/**'
      - 'test2/**'

env:
  PROJECT_ID: prj-airindia-poc-01
  GAR_LOCATION: asia-south1
  REGION: asia-south1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/13579727091/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
          service_account: 'sql-poc@prj-airindia-poc-01.iam.gserviceaccount.com'
          access_token_lifetime: '300s'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          if [[ -n $(git diff --name-only HEAD^ -- 'test1/') ]]; then
            docker build -t "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test1:latest" ./test1
            docker push "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test1:latest"
          elif [[ -n $(git diff --name-only HEAD^ -- 'test2/') ]]; then
            docker build -t "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:latest" ./test2
            docker push "asia-south1-docker.pkg.dev/prj-airindia-poc-01/cloud-run-source-deploy/test2:latest"
          fi

